# Generated by Django 4.2.8 on 2023-12-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UrlMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_url", models.URLField(verbose_name="Original URL")),
                (
                    "short_url",
                    models.CharField(
                        max_length=6, unique=True, verbose_name="Short URL"
                    ),
                ),
            ],
            options={
                "verbose_name": "Url Mapping",
                "db_table": "url_mapping",
            },
        ),
    ]
